# Docker Swarm Stack Configuration for MCP Python SDK
# Simplified modular configuration with service composition


services:
  # Main MCP Application
  mcp-app:
    image: ${DEV_CONTAINER_NAME:-mcp-python-sdk-dev}:latest
    deploy:
      replicas: ${SWARM_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '${CONTAINER_CPU_LIMIT:-0}'
          memory: ${CONTAINER_MEMORY_LIMIT:-48G}
        reservations:
          cpus: '4.0'
          memory: ${CONTAINER_MEMORY_RESERVATION:-16G}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - REDIS_URL=redis://redis:6379
      - MCP_SERVER_PORT=${MCP_SERVER_PORT:-5000}
    ports:
      - "${MCP_SERVER_PORT:-5000}:5000"
      - "${FASTAPI_PORT:-8000}:8000"
    volumes:
      - mcp-cache:/opt/mcp-cache
      - python-wheels:/opt/python-wheels
    runtime: nvidia
    privileged: true
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidiactl:/dev/nvidiactl"
    networks:
      - mcp-network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mcp-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: overlay
    attachable: true

volumes:
  mcp-cache:
    external: true
  python-wheels:
    external: true
  postgres-data:
    external: true
  redis-data:
    external: true
