# PostgreSQL Database Service Configuration
# High-performance PostgreSQL for Docker Swarm

version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_SHARED_BUFFERS=${POSTGRES_SHARED_BUFFERS:-1GB}
      - POSTGRES_EFFECTIVE_CACHE_SIZE=${POSTGRES_EFFECTIVE_CACHE_SIZE:-3GB}
      - POSTGRES_MAINTENANCE_WORK_MEM=${POSTGRES_MAINTENANCE_WORK_MEM:-256MB}
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS:-200}
      - POSTGRES_MAX_WORKER_PROCESSES=${POSTGRES_MAX_WORKER_PROCESSES:-32}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-config:/etc/postgresql
    command: >
      postgres
      -c shared_buffers=${POSTGRES_SHARED_BUFFERS:-1GB}
      -c effective_cache_size=${POSTGRES_EFFECTIVE_CACHE_SIZE:-3GB}
      -c maintenance_work_mem=${POSTGRES_MAINTENANCE_WORK_MEM:-256MB}
      -c max_connections=${POSTGRES_MAX_CONNECTIONS:-200}
      -c max_worker_processes=${POSTGRES_MAX_WORKER_PROCESSES:-32}
      -c wal_buffers=16MB
      -c checkpoint_completion_target=0.9
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    networks:
      - mcp-network

volumes:
  postgres-data:
    driver: local
  postgres-config:
    driver: local

networks:
  mcp-network:
    external: true
