# Redis Cache Service Configuration
# High-performance Redis for Docker Swarm
# Uses global configuration variables with GLOBAL_ prefix

services:
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "${GLOBAL_CPU_LIMIT:-0}"
          memory: "${GLOBAL_MEMORY_LIMIT:-0}"
        reservations:
          cpus: '1.0'
          memory: 2G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >
      redis-server
      --maxmemory ${GLOBAL_REDIS_MAXMEMORY:-4gb}
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --tcp-keepalive 60
      --tcp-backlog 511
    ports:
      - "${GLOBAL_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - mcp-network

volumes:
  redis-data:
    driver: local

networks:
  mcp-network:
    external: true