# App Service Configuration - Uses Global Templates
services:
  app:
    <<: *app-service
    build:
      context: ../../..
      dockerfile: .devcontainer/docker/Dockerfile.main
      target: runtime
      args:
        GLOBAL_BUILDKIT_INLINE_CACHE: "1"
        GLOBAL_DOCKER_BUILDKIT: "1"
        GLOBAL_PYTHONOPTIMIZE: "2"
        GLOBAL_PYTHONHASHSEED: "0"
      cache_from:
        - ghcr.io/modelcontextprotocol/python-sdk:cache
    command: sleep infinity
