# PostgreSQL Service Configuration - Uses Global Templates
services:
  db:
    <<: *postgres-service
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s