version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
      --tcp-keepalive 60
      --tcp-backlog 511
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          size: 1G
          mode: 1777
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
